namespace: dev

image:
  registry: "349036691410.dkr.ecr.eu-central-1.amazonaws.com"
  tag: "13"
  pullPolicy: IfNotPresent

aws:
  region: eu-central-1

secrets:
  dbSecretArn: "arn:aws:secretsmanager:eu-central-1:349036691410:secret:rds!db-84b0f841-d84e-441f-82de-0d21e68dc7e9-kmfdRr"
  rabbitmqSecretName: "taskflow/dev/rabbitmq/v1"

database:
  host: "taskflow-dev-postgres.c7wwocm2et85.eu-central-1.rds.amazonaws.com"
  port: "5432"
  name: "taskflow"

rabbitmq:
  host: "b-7bb640aa-4619-40c5-b715-bcf94f29134a.mq.eu-central-1.on.aws"
  port: "5671"

ingress:
  enabled: true
  className: alb
  host: "" 
  scheme: internet-facing

services:
  frontend:
    image: taskflow-dev/frontend

  api-gateway:
    image: taskflow-dev/api-gateway

  auth-service:
    image: taskflow-dev/auth-service

  user-service:
    image: taskflow-dev/user-service

  task-service:
    image: taskflow-dev/task-service

  project-service:
    image: taskflow-dev/project-service

  notification-service:
    image: taskflow-dev/notification-service

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  cpuUtilization: 70