apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: taskflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: masudrana09/taskflow-frontend:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80