apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: taskflow
data:
  PORT: "3000"
  AUTH_SERVICE_URL: "http://auth-service:3001"
  USER_SERVICE_URL: "http://user-service:3002"
  TASK_SERVICE_URL: "http://task-service:3003"
  PROJECT_SERVICE_URL: "http://project-service:3004"
  NOTIFICATION_SERVICE_URL: "http://notification-service:3005"