apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: taskflow
spec:
  selector:
    app: notification-service
  ports:
    - port: 3005
      targetPort: 3005
  type: ClusterIP