apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-service
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-service
  template:
    metadata:
      labels:
        app: task-service
    spec:
      containers:
        - name: task-service
          image: masudrana09/taskflow-task-service:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3003
          envFrom:
            - configMapRef:
                name: task-service-config
            - secretRef:
                name: taskflow-db-secret
            - secretRef:
                name: taskflow-rabbitmq-secret
          readinessProbe:
            httpGet:
              path: /health
              port: 3003
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 3003
            initialDelaySeconds: 20
            periodSeconds: 10