{{- range $name, $svc := .Values.services }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.namespace }}
spec:
  replicas: {{ $svc.replicas }}
  selector:
    matchLabels:
      app: {{ $name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
    spec:
      containers:
        - name: {{ $name }}
          image: "{{ $.Values.image.registry }}/{{ $svc.image }}:{{ $.Values.image.tag }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          ports:
            - containerPort: {{ $svc.port }}

          envFrom:
            - configMapRef:
                name: {{ $name }}-config

            {{- if or (eq $name "authService") (eq $name "userService") (eq $name "taskService") (eq $name "projectService") }}
            - secretRef:
                name: taskflow-db-secret
            {{- end }}

            {{- if or (eq $name "taskService") (eq $name "notificationService") }}
            - secretRef:
                name: taskflow-rabbitmq-secret
            {{- end }}

          readinessProbe:
            httpGet:
              path: /health
              port: {{ $svc.port }}
            initialDelaySeconds: 10
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /health
              port: {{ $svc.port }}
            initialDelaySeconds: 20
            periodSeconds: 10

          resources:
            requests:
              cpu: {{ $.Values.resources.requests.cpu }}
              memory: {{ $.Values.resources.requests.memory }}
            limits:
              cpu: {{ $.Values.resources.limits.cpu }}
              memory: {{ $.Values.resources.limits.memory }}
---
{{- end }}