{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: taskflow-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    alb.ingress.kubernetes.io/scheme: {{ .Values.ingress.scheme }} # Load balancer scheme (internet-facing or internal)
    alb.ingress.kubernetes.io/target-type: ip # Target type (ip)
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]' # Listen on port 80 for HTTP traffic

spec:
  ingressClassName: {{ .Values.ingress.className }}

  rules:
    - http:
        paths:

          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 4000

          - path: /tasks
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 4000

          - path: /projects
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 4000

          - path: /notifications
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 4000

          - path: /            # Catch-all for frontend routes that didn't match the above API paths
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
{{- end }}