apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-gateway-monitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - dev

  selector:
    matchLabels:
      app: api-gateway

  endpoints:
    - port: http
      path: /metrics
      interval: 15s