apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-service
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-service
  template:
    metadata:
      labels:
        app: project-service
    spec:
      containers:
        - name: project-service
          image: masudrana09/taskflow-project-service:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3004
          envFrom:
            - configMapRef:
                name: project-service-config
            - secretRef:
                name: taskflow-db-secret
          readinessProbe:
            httpGet:
              path: /health
              port: 3004
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 3004
            initialDelaySeconds: 20
            periodSeconds: 10