apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: taskflow-db-secret
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: taskflow-db-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_USER
      remoteRef:
        key: {{ .Values.secrets.dbSecretArn | quote }}
        property: username

    - secretKey: DB_PASSWORD
      remoteRef:
        key: {{ .Values.secrets.dbSecretArn | quote }}
        property: password