apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: taskflow-rabbitmq-secret
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: taskflow-rabbitmq-secret
    creationPolicy: Owner
  data:
    - secretKey: RABBITMQ_USERNAME
      remoteRef:
        key: {{ .Values.secrets.rabbitmqSecretName | quote }}
        property: username

    - secretKey: RABBITMQ_PASSWORD
      remoteRef:
        key: {{ .Values.secrets.rabbitmqSecretName | quote }}
        property: password

    - secretKey: RABBITMQ_PORT
      remoteRef:
        key: {{ .Values.secrets.rabbitmqSecretName | quote }}
        property: port