apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: taskflow-rabbitmq-secret
  namespace: dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: taskflow-rabbitmq-secret
    creationPolicy: Owner
  data:
    - secretKey: RABBITMQ_USERNAME
      remoteRef:
        key: taskflow/dev/rabbitmq
        property: username

    - secretKey: RABBITMQ_PASSWORD
      remoteRef:
        key: taskflow/dev/rabbitmq
        property: password

    - secretKey: RABBITMQ_HOST
      remoteRef:
        key: taskflow/dev/rabbitmq
        property: host

    - secretKey: RABBITMQ_PORT
      remoteRef:
        key: taskflow/dev/rabbitmq
        property: port