apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: taskflow-dev
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/masud0932/taskflow-microservices-project.git
    targetRevision: main
    path: taskflow-gitops-manifests/helm-charts/taskflow
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc # in-cluster URL
    namespace: dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true