apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: taskflow-dev
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/masud0932/taskflow-microservices-k8s-project.git
    targetRevision: main
    path: taskflow-gitops-manifests/helm-charts/taskflow

  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true